module.exports = [
  // ─── INDIA ───
  { iata: 'DEL', name: 'Delhi Indira Gandhi', city: 'Delhi', country: 'India', rank: 100 },
  { iata: 'BOM', name: 'Mumbai Chhatrapati Shivaji', city: 'Mumbai', country: 'India', rank: 100 },
  { iata: 'BLR', name: 'Bengaluru Kempegowda', city: 'Bengaluru', country: 'India', rank: 95 },
  { iata: 'MAA', name: 'Chennai International', city: 'Chennai', country: 'India', rank: 90 },
  { iata: 'CCU', name: 'Kolkata Netaji', city: 'Kolkata', country: 'India', rank: 85 },
  { iata: 'HYD', name: 'Hyderabad Rajiv Gandhi', city: 'Hyderabad', country: 'India', rank: 85 },
  { iata: 'GOI', name: 'Goa Dabolim', city: 'Goa', country: 'India', rank: 75 },
  { iata: 'COK', name: 'Kochi International', city: 'Kochi', country: 'India', rank: 70 },
  { iata: 'AMD', name: 'Ahmedabad Sardar Vallabhbhai Patel', city: 'Ahmedabad', country: 'India', rank: 70 },
  { iata: 'PNQ', name: 'Pune', city: 'Pune', country: 'India', rank: 65 },
  { iata: 'TRV', name: 'Trivandrum International', city: 'Thiruvananthapuram', country: 'India', rank: 60 },
  { iata: 'JAI', name: 'Jaipur International', city: 'Jaipur', country: 'India', rank: 60 },
  { iata: 'LKO', name: 'Lucknow Chaudhary Charan Singh', city: 'Lucknow', country: 'India', rank: 55 },
  { iata: 'IXC', name: 'Chandigarh', city: 'Chandigarh', country: 'India', rank: 50 },
  { iata: 'IXB', name: 'Bagdogra', city: 'Siliguri', country: 'India', rank: 45 },
  { iata: 'GAU', name: 'Guwahati Lokpriya Gopinath Bordoloi', city: 'Guwahati', country: 'India', rank: 50 },
  { iata: 'NAG', name: 'Nagpur Dr. Babasaheb Ambedkar', city: 'Nagpur', country: 'India', rank: 50 },
  { iata: 'IXM', name: 'Madurai', city: 'Madurai', country: 'India', rank: 45 },
  { iata: 'VNS', name: 'Varanasi Lal Bahadur Shastri', city: 'Varanasi', country: 'India', rank: 50 },
  { iata: 'SXR', name: 'Srinagar', city: 'Srinagar', country: 'India', rank: 50 },

  // ─── UNITED KINGDOM ───
  { iata: 'LHR', name: 'London Heathrow', city: 'London', country: 'United Kingdom', rank: 100 },
  { iata: 'LGW', name: 'London Gatwick', city: 'London', country: 'United Kingdom', rank: 90 },
  { iata: 'STN', name: 'London Stansted', city: 'London', country: 'United Kingdom', rank: 80 },
  { iata: 'LTN', name: 'London Luton', city: 'London', country: 'United Kingdom', rank: 75 },
  { iata: 'LCY', name: 'London City', city: 'London', country: 'United Kingdom', rank: 70 },
  { iata: 'MAN', name: 'Manchester', city: 'Manchester', country: 'United Kingdom', rank: 85 },
  { iata: 'EDI', name: 'Edinburgh', city: 'Edinburgh', country: 'United Kingdom', rank: 75 },
  { iata: 'GLA', name: 'Glasgow', city: 'Glasgow', country: 'United Kingdom', rank: 70 },
  { iata: 'BHX', name: 'Birmingham', city: 'Birmingham', country: 'United Kingdom', rank: 70 },
  { iata: 'BRS', name: 'Bristol', city: 'Bristol', country: 'United Kingdom', rank: 65 },
  { iata: 'NCL', name: 'Newcastle', city: 'Newcastle', country: 'United Kingdom', rank: 60 },
  { iata: 'LPL', name: 'Liverpool John Lennon', city: 'Liverpool', country: 'United Kingdom', rank: 60 },
  { iata: 'BFS', name: 'Belfast International', city: 'Belfast', country: 'United Kingdom', rank: 55 },
  { iata: 'ABZ', name: 'Aberdeen', city: 'Aberdeen', country: 'United Kingdom', rank: 50 },

  // ─── IRELAND ───
  { iata: 'DUB', name: 'Dublin', city: 'Dublin', country: 'Ireland', rank: 85 },
  { iata: 'ORK', name: 'Cork', city: 'Cork', country: 'Ireland', rank: 55 },
  { iata: 'SNN', name: 'Shannon', city: 'Shannon', country: 'Ireland', rank: 50 },

  // ─── FRANCE ───
  { iata: 'CDG', name: 'Paris Charles de Gaulle', city: 'Paris', country: 'France', rank: 100 },
  { iata: 'ORY', name: 'Paris Orly', city: 'Paris', country: 'France', rank: 85 },
  { iata: 'BVA', name: 'Paris Beauvais', city: 'Paris', country: 'France', rank: 60 },
  { iata: 'NCE', name: 'Nice Côte d\'Azur', city: 'Nice', country: 'France', rank: 75 },
  { iata: 'LYS', name: 'Lyon Saint-Exupéry', city: 'Lyon', country: 'France', rank: 70 },
  { iata: 'MRS', name: 'Marseille Provence', city: 'Marseille', country: 'France', rank: 70 },
  { iata: 'TLS', name: 'Toulouse Blagnac', city: 'Toulouse', country: 'France', rank: 65 },
  { iata: 'BOD', name: 'Bordeaux Mérignac', city: 'Bordeaux', country: 'France', rank: 60 },
  { iata: 'NTE', name: 'Nantes Atlantique', city: 'Nantes', country: 'France', rank: 60 },

  // ─── GERMANY ───
  { iata: 'FRA', name: 'Frankfurt am Main', city: 'Frankfurt', country: 'Germany', rank: 100 },
  { iata: 'MUC', name: 'Munich Franz Josef Strauss', city: 'Munich', country: 'Germany', rank: 95 },
  { iata: 'BER', name: 'Berlin Brandenburg', city: 'Berlin', country: 'Germany', rank: 90 },
  { iata: 'DUS', name: 'Düsseldorf', city: 'Düsseldorf', country: 'Germany', rank: 80 },
  { iata: 'HAM', name: 'Hamburg', city: 'Hamburg', country: 'Germany', rank: 75 },
  { iata: 'CGN', name: 'Cologne Bonn', city: 'Cologne', country: 'Germany', rank: 70 },
  { iata: 'STR', name: 'Stuttgart', city: 'Stuttgart', country: 'Germany', rank: 70 },
  { iata: 'NUE', name: 'Nuremberg', city: 'Nuremberg', country: 'Germany', rank: 60 },
  { iata: 'HAJ', name: 'Hannover', city: 'Hannover', country: 'Germany', rank: 55 },
  { iata: 'LEJ', name: 'Leipzig/Halle', city: 'Leipzig', country: 'Germany', rank: 55 },

  // ─── ITALY ───
  { iata: 'FCO', name: 'Rome Fiumicino', city: 'Rome', country: 'Italy', rank: 95 },
  { iata: 'CIA', name: 'Rome Ciampino', city: 'Rome', country: 'Italy', rank: 65 },
  { iata: 'MXP', name: 'Milan Malpensa', city: 'Milan', country: 'Italy', rank: 90 },
  { iata: 'LIN', name: 'Milan Linate', city: 'Milan', country: 'Italy', rank: 75 },
  { iata: 'BGY', name: 'Milan Bergamo', city: 'Milan', country: 'Italy', rank: 70 },
  { iata: 'VCE', name: 'Venice Marco Polo', city: 'Venice', country: 'Italy', rank: 75 },
  { iata: 'NAP', name: 'Naples', city: 'Naples', country: 'Italy', rank: 70 },
  { iata: 'BLQ', name: 'Bologna Marconi', city: 'Bologna', country: 'Italy', rank: 65 },
  { iata: 'FLR', name: 'Florence Peretola', city: 'Florence', country: 'Italy', rank: 65 },
  { iata: 'CTA', name: 'Catania Fontanarossa', city: 'Catania', country: 'Italy', rank: 60 },
  { iata: 'PMO', name: 'Palermo Falcone Borsellino', city: 'Palermo', country: 'Italy', rank: 60 },
  { iata: 'PSA', name: 'Pisa Galileo Galilei', city: 'Pisa', country: 'Italy', rank: 60 },
  { iata: 'TRN', name: 'Turin', city: 'Turin', country: 'Italy', rank: 55 },

  // ─── SPAIN ───
  { iata: 'MAD', name: 'Madrid Barajas', city: 'Madrid', country: 'Spain', rank: 95 },
  { iata: 'BCN', name: 'Barcelona El Prat', city: 'Barcelona', country: 'Spain', rank: 95 },
  { iata: 'PMI', name: 'Palma de Mallorca', city: 'Palma de Mallorca', country: 'Spain', rank: 80 },
  { iata: 'AGP', name: 'Málaga Costa del Sol', city: 'Málaga', country: 'Spain', rank: 75 },
  { iata: 'ALC', name: 'Alicante Elche', city: 'Alicante', country: 'Spain', rank: 70 },
  { iata: 'VLC', name: 'Valencia', city: 'Valencia', country: 'Spain', rank: 70 },
  { iata: 'SVQ', name: 'Seville', city: 'Seville', country: 'Spain', rank: 65 },
  { iata: 'BIO', name: 'Bilbao', city: 'Bilbao', country: 'Spain', rank: 60 },
  { iata: 'IBZ', name: 'Ibiza', city: 'Ibiza', country: 'Spain', rank: 65 },
  { iata: 'TFS', name: 'Tenerife South', city: 'Tenerife', country: 'Spain', rank: 65 },
  { iata: 'LPA', name: 'Gran Canaria', city: 'Las Palmas', country: 'Spain', rank: 60 },

  // ─── PORTUGAL ───
  { iata: 'LIS', name: 'Lisbon Portela', city: 'Lisbon', country: 'Portugal', rank: 85 },
  { iata: 'OPO', name: 'Porto', city: 'Porto', country: 'Portugal', rank: 70 },
  { iata: 'FAO', name: 'Faro', city: 'Faro', country: 'Portugal', rank: 60 },
  { iata: 'FNC', name: 'Funchal Madeira', city: 'Funchal', country: 'Portugal', rank: 55 },

  // ─── NETHERLANDS / BELGIUM ───
  { iata: 'AMS', name: 'Amsterdam Schiphol', city: 'Amsterdam', country: 'Netherlands', rank: 100 },
  { iata: 'EIN', name: 'Eindhoven', city: 'Eindhoven', country: 'Netherlands', rank: 60 },
  { iata: 'RTM', name: 'Rotterdam The Hague', city: 'Rotterdam', country: 'Netherlands', rank: 55 },
  { iata: 'BRU', name: 'Brussels', city: 'Brussels', country: 'Belgium', rank: 80 },
  { iata: 'CRL', name: 'Brussels Charleroi', city: 'Brussels', country: 'Belgium', rank: 60 },

  // ─── SWITZERLAND / AUSTRIA ───
  { iata: 'ZRH', name: 'Zurich Kloten', city: 'Zurich', country: 'Switzerland', rank: 85 },
  { iata: 'GVA', name: 'Geneva', city: 'Geneva', country: 'Switzerland', rank: 75 },
  { iata: 'BSL', name: 'Basel-Mulhouse-Freiburg', city: 'Basel', country: 'Switzerland', rank: 65 },
  { iata: 'VIE', name: 'Vienna International', city: 'Vienna', country: 'Austria', rank: 80 },
  { iata: 'SZG', name: 'Salzburg', city: 'Salzburg', country: 'Austria', rank: 55 },
  { iata: 'INN', name: 'Innsbruck', city: 'Innsbruck', country: 'Austria', rank: 50 },

  // ─── SCANDINAVIA ───
  { iata: 'CPH', name: 'Copenhagen Kastrup', city: 'Copenhagen', country: 'Denmark', rank: 85 },
  { iata: 'BLL', name: 'Billund', city: 'Billund', country: 'Denmark', rank: 55 },
  { iata: 'ARN', name: 'Stockholm Arlanda', city: 'Stockholm', country: 'Sweden', rank: 85 },
  { iata: 'GOT', name: 'Gothenburg Landvetter', city: 'Gothenburg', country: 'Sweden', rank: 60 },
  { iata: 'MMX', name: 'Malmö', city: 'Malmö', country: 'Sweden', rank: 50 },
  { iata: 'OSL', name: 'Oslo Gardermoen', city: 'Oslo', country: 'Norway', rank: 80 },
  { iata: 'BGO', name: 'Bergen Flesland', city: 'Bergen', country: 'Norway', rank: 60 },
  { iata: 'TRD', name: 'Trondheim Værnes', city: 'Trondheim', country: 'Norway', rank: 50 },
  { iata: 'HEL', name: 'Helsinki Vantaa', city: 'Helsinki', country: 'Finland', rank: 80 },
  { iata: 'KEF', name: 'Reykjavík Keflavík', city: 'Reykjavik', country: 'Iceland', rank: 70 },

  // ─── EASTERN EUROPE ───
  { iata: 'WAW', name: 'Warsaw Chopin', city: 'Warsaw', country: 'Poland', rank: 80 },
  { iata: 'KRK', name: 'Krakow John Paul II', city: 'Krakow', country: 'Poland', rank: 65 },
  { iata: 'GDN', name: 'Gdansk Lech Walesa', city: 'Gdansk', country: 'Poland', rank: 55 },
  { iata: 'WRO', name: 'Wroclaw Copernicus', city: 'Wroclaw', country: 'Poland', rank: 50 },
  { iata: 'PRG', name: 'Prague Václav Havel', city: 'Prague', country: 'Czech Republic', rank: 80 },
  { iata: 'BUD', name: 'Budapest Ferenc Liszt', city: 'Budapest', country: 'Hungary', rank: 75 },
  { iata: 'BTS', name: 'Bratislava', city: 'Bratislava', country: 'Slovakia', rank: 50 },
  { iata: 'OTP', name: 'Bucharest Henri Coanda', city: 'Bucharest', country: 'Romania', rank: 70 },
  { iata: 'SOF', name: 'Sofia', city: 'Sofia', country: 'Bulgaria', rank: 65 },
  { iata: 'BEG', name: 'Belgrade Nikola Tesla', city: 'Belgrade', country: 'Serbia', rank: 65 },
  { iata: 'ZAG', name: 'Zagreb Franjo Tudman', city: 'Zagreb', country: 'Croatia', rank: 60 },
  { iata: 'SPU', name: 'Split', city: 'Split', country: 'Croatia', rank: 55 },
  { iata: 'DBV', name: 'Dubrovnik', city: 'Dubrovnik', country: 'Croatia', rank: 55 },
  { iata: 'LJU', name: 'Ljubljana Joze Pucnik', city: 'Ljubljana', country: 'Slovenia', rank: 50 },
  { iata: 'KIV', name: 'Chisinau', city: 'Chisinau', country: 'Moldova', rank: 45 },
  { iata: 'TLL', name: 'Tallinn Lennart Meri', city: 'Tallinn', country: 'Estonia', rank: 55 },
  { iata: 'RIX', name: 'Riga', city: 'Riga', country: 'Latvia', rank: 60 },
  { iata: 'VNO', name: 'Vilnius', city: 'Vilnius', country: 'Lithuania', rank: 55 },

  // ─── RUSSIA / CIS ───
  { iata: 'SVO', name: 'Moscow Sheremetyevo', city: 'Moscow', country: 'Russia', rank: 90 },
  { iata: 'DME', name: 'Moscow Domodedovo', city: 'Moscow', country: 'Russia', rank: 85 },
  { iata: 'VKO', name: 'Moscow Vnukovo', city: 'Moscow', country: 'Russia', rank: 75 },
  { iata: 'LED', name: 'St. Petersburg Pulkovo', city: 'St. Petersburg', country: 'Russia', rank: 80 },
  { iata: 'KZN', name: 'Kazan', city: 'Kazan', country: 'Russia', rank: 60 },
  { iata: 'AER', name: 'Sochi', city: 'Sochi', country: 'Russia', rank: 60 },
  { iata: 'KBP', name: 'Kyiv Boryspil', city: 'Kyiv', country: 'Ukraine', rank: 70 },
  { iata: 'MSQ', name: 'Minsk', city: 'Minsk', country: 'Belarus', rank: 55 },
  { iata: 'TBS', name: 'Tbilisi', city: 'Tbilisi', country: 'Georgia', rank: 55 },
  { iata: 'EVN', name: 'Yerevan Zvartnots', city: 'Yerevan', country: 'Armenia', rank: 55 },
  { iata: 'GYD', name: 'Baku Heydar Aliyev', city: 'Baku', country: 'Azerbaijan', rank: 60 },
  { iata: 'ALA', name: 'Almaty', city: 'Almaty', country: 'Kazakhstan', rank: 65 },
  { iata: 'NQZ', name: 'Astana Nursultan Nazarbayev', city: 'Astana', country: 'Kazakhstan', rank: 60 },
  { iata: 'TAS', name: 'Tashkent', city: 'Tashkent', country: 'Uzbekistan', rank: 60 },

  // ─── GREECE / CYPRUS / MALTA ───
  { iata: 'ATH', name: 'Athens Eleftherios Venizelos', city: 'Athens', country: 'Greece', rank: 80 },
  { iata: 'SKG', name: 'Thessaloniki Macedonia', city: 'Thessaloniki', country: 'Greece', rank: 65 },
  { iata: 'HER', name: 'Heraklion', city: 'Heraklion', country: 'Greece', rank: 65 },
  { iata: 'RHO', name: 'Rhodes', city: 'Rhodes', country: 'Greece', rank: 60 },
  { iata: 'JMK', name: 'Mykonos', city: 'Mykonos', country: 'Greece', rank: 55 },
  { iata: 'JTR', name: 'Santorini', city: 'Santorini', country: 'Greece', rank: 55 },
  { iata: 'LCA', name: 'Larnaca', city: 'Larnaca', country: 'Cyprus', rank: 65 },
  { iata: 'PFO', name: 'Paphos', city: 'Paphos', country: 'Cyprus', rank: 55 },
  { iata: 'MLA', name: 'Malta', city: 'Malta', country: 'Malta', rank: 60 },

  // ─── TURKEY ───
  { iata: 'IST', name: 'Istanbul', city: 'Istanbul', country: 'Turkey', rank: 95 },
  { iata: 'SAW', name: 'Istanbul Sabiha Gökçen', city: 'Istanbul', country: 'Turkey', rank: 80 },
  { iata: 'AYT', name: 'Antalya', city: 'Antalya', country: 'Turkey', rank: 75 },
  { iata: 'ESB', name: 'Ankara Esenboga', city: 'Ankara', country: 'Turkey', rank: 65 },
  { iata: 'ADB', name: 'Izmir Adnan Menderes', city: 'Izmir', country: 'Turkey', rank: 65 },
  { iata: 'BJV', name: 'Bodrum Milas', city: 'Bodrum', country: 'Turkey', rank: 55 },

  // ─── MIDDLE EAST ───
  { iata: 'DXB', name: 'Dubai International', city: 'Dubai', country: 'UAE', rank: 100 },
  { iata: 'DWC', name: 'Dubai Al Maktoum', city: 'Dubai', country: 'UAE', rank: 65 },
  { iata: 'AUH', name: 'Abu Dhabi International', city: 'Abu Dhabi', country: 'UAE', rank: 85 },
  { iata: 'SHJ', name: 'Sharjah', city: 'Sharjah', country: 'UAE', rank: 70 },
  { iata: 'DOH', name: 'Doha Hamad', city: 'Doha', country: 'Qatar', rank: 90 },
  { iata: 'KWI', name: 'Kuwait', city: 'Kuwait City', country: 'Kuwait', rank: 75 },
  { iata: 'BAH', name: 'Bahrain', city: 'Manama', country: 'Bahrain', rank: 70 },
  { iata: 'MCT', name: 'Muscat', city: 'Muscat', country: 'Oman', rank: 70 },
  { iata: 'RUH', name: 'Riyadh King Khalid', city: 'Riyadh', country: 'Saudi Arabia', rank: 85 },
  { iata: 'JED', name: 'Jeddah King Abdulaziz', city: 'Jeddah', country: 'Saudi Arabia', rank: 80 },
  { iata: 'DMM', name: 'Dammam King Fahd', city: 'Dammam', country: 'Saudi Arabia', rank: 65 },
  { iata: 'MED', name: 'Madinah Prince Mohammad', city: 'Madinah', country: 'Saudi Arabia', rank: 60 },
  { iata: 'AMM', name: 'Amman Queen Alia', city: 'Amman', country: 'Jordan', rank: 70 },
  { iata: 'BEY', name: 'Beirut Rafic Hariri', city: 'Beirut', country: 'Lebanon', rank: 65 },
  { iata: 'TLV', name: 'Tel Aviv Ben Gurion', city: 'Tel Aviv', country: 'Israel', rank: 80 },
  { iata: 'IKA', name: 'Tehran Imam Khomeini', city: 'Tehran', country: 'Iran', rank: 70 },

  // ─── NORTH AFRICA ───
  { iata: 'CAI', name: 'Cairo International', city: 'Cairo', country: 'Egypt', rank: 85 },
  { iata: 'HRG', name: 'Hurghada', city: 'Hurghada', country: 'Egypt', rank: 65 },
  { iata: 'SSH', name: 'Sharm El Sheikh', city: 'Sharm El Sheikh', country: 'Egypt', rank: 60 },
  { iata: 'CMN', name: 'Casablanca Mohammed V', city: 'Casablanca', country: 'Morocco', rank: 75 },
  { iata: 'RAK', name: 'Marrakech Menara', city: 'Marrakech', country: 'Morocco', rank: 70 },
  { iata: 'AGA', name: 'Agadir Al Massira', city: 'Agadir', country: 'Morocco', rank: 55 },
  { iata: 'TUN', name: 'Tunis Carthage', city: 'Tunis', country: 'Tunisia', rank: 65 },
  { iata: 'ALG', name: 'Algiers Houari Boumediene', city: 'Algiers', country: 'Algeria', rank: 65 },

  // ─── SUB-SAHARAN AFRICA ───
  { iata: 'JNB', name: 'Johannesburg O.R. Tambo', city: 'Johannesburg', country: 'South Africa', rank: 85 },
  { iata: 'CPT', name: 'Cape Town', city: 'Cape Town', country: 'South Africa', rank: 80 },
  { iata: 'DUR', name: 'Durban King Shaka', city: 'Durban', country: 'South Africa', rank: 65 },
  { iata: 'NBO', name: 'Nairobi Jomo Kenyatta', city: 'Nairobi', country: 'Kenya', rank: 75 },
  { iata: 'MBA', name: 'Mombasa Moi', city: 'Mombasa', country: 'Kenya', rank: 55 },
  { iata: 'DAR', name: 'Dar es Salaam Julius Nyerere', city: 'Dar es Salaam', country: 'Tanzania', rank: 60 },
  { iata: 'ZNZ', name: 'Zanzibar', city: 'Zanzibar', country: 'Tanzania', rank: 55 },
  { iata: 'ADD', name: 'Addis Ababa Bole', city: 'Addis Ababa', country: 'Ethiopia', rank: 75 },
  { iata: 'LOS', name: 'Lagos Murtala Muhammed', city: 'Lagos', country: 'Nigeria', rank: 75 },
  { iata: 'ABV', name: 'Abuja Nnamdi Azikiwe', city: 'Abuja', country: 'Nigeria', rank: 65 },
  { iata: 'ACC', name: 'Accra Kotoka', city: 'Accra', country: 'Ghana', rank: 65 },
  { iata: 'DKR', name: 'Dakar Blaise Diagne', city: 'Dakar', country: 'Senegal', rank: 60 },
  { iata: 'EBB', name: 'Entebbe', city: 'Kampala', country: 'Uganda', rank: 55 },
  { iata: 'KGL', name: 'Kigali', city: 'Kigali', country: 'Rwanda', rank: 55 },
  { iata: 'MRU', name: 'Mauritius Sir Seewoosagur Ramgoolam', city: 'Mauritius', country: 'Mauritius', rank: 60 },
  { iata: 'SEZ', name: 'Seychelles', city: 'Mahé', country: 'Seychelles', rank: 55 },
  { iata: 'TNR', name: 'Antananarivo Ivato', city: 'Antananarivo', country: 'Madagascar', rank: 50 },

  // ─── EAST ASIA ───
  { iata: 'NRT', name: 'Tokyo Narita', city: 'Tokyo', country: 'Japan', rank: 95 },
  { iata: 'HND', name: 'Tokyo Haneda', city: 'Tokyo', country: 'Japan', rank: 95 },
  { iata: 'KIX', name: 'Osaka Kansai', city: 'Osaka', country: 'Japan', rank: 80 },
  { iata: 'ITM', name: 'Osaka Itami', city: 'Osaka', country: 'Japan', rank: 65 },
  { iata: 'NGO', name: 'Nagoya Chubu Centrair', city: 'Nagoya', country: 'Japan', rank: 70 },
  { iata: 'FUK', name: 'Fukuoka', city: 'Fukuoka', country: 'Japan', rank: 65 },
  { iata: 'CTS', name: 'Sapporo New Chitose', city: 'Sapporo', country: 'Japan', rank: 65 },
  { iata: 'OKA', name: 'Okinawa Naha', city: 'Okinawa', country: 'Japan', rank: 60 },
  { iata: 'ICN', name: 'Seoul Incheon', city: 'Seoul', country: 'South Korea', rank: 95 },
  { iata: 'GMP', name: 'Seoul Gimpo', city: 'Seoul', country: 'South Korea', rank: 70 },
  { iata: 'PUS', name: 'Busan Gimhae', city: 'Busan', country: 'South Korea', rank: 65 },
  { iata: 'CJU', name: 'Jeju', city: 'Jeju', country: 'South Korea', rank: 60 },
  { iata: 'PEK', name: 'Beijing Capital', city: 'Beijing', country: 'China', rank: 95 },
  { iata: 'PKX', name: 'Beijing Daxing', city: 'Beijing', country: 'China', rank: 85 },
  { iata: 'PVG', name: 'Shanghai Pudong', city: 'Shanghai', country: 'China', rank: 95 },
  { iata: 'SHA', name: 'Shanghai Hongqiao', city: 'Shanghai', country: 'China', rank: 80 },
  { iata: 'CAN', name: 'Guangzhou Baiyun', city: 'Guangzhou', country: 'China', rank: 85 },
  { iata: 'SZX', name: 'Shenzhen Baoan', city: 'Shenzhen', country: 'China', rank: 80 },
  { iata: 'CTU', name: 'Chengdu Shuangliu', city: 'Chengdu', country: 'China', rank: 75 },
  { iata: 'KMG', name: 'Kunming Changshui', city: 'Kunming', country: 'China', rank: 70 },
  { iata: 'XIY', name: 'Xi\'an Xianyang', city: 'Xi\'an', country: 'China', rank: 70 },
  { iata: 'CKG', name: 'Chongqing Jiangbei', city: 'Chongqing', country: 'China', rank: 70 },
  { iata: 'HGH', name: 'Hangzhou Xiaoshan', city: 'Hangzhou', country: 'China', rank: 70 },
  { iata: 'NKG', name: 'Nanjing Lukou', city: 'Nanjing', country: 'China', rank: 65 },
  { iata: 'WUH', name: 'Wuhan Tianhe', city: 'Wuhan', country: 'China', rank: 65 },
  { iata: 'XMN', name: 'Xiamen Gaoqi', city: 'Xiamen', country: 'China', rank: 65 },
  { iata: 'TAO', name: 'Qingdao Liuting', city: 'Qingdao', country: 'China', rank: 60 },
  { iata: 'DLC', name: 'Dalian Zhoushuizi', city: 'Dalian', country: 'China', rank: 60 },
  { iata: 'HKG', name: 'Hong Kong International', city: 'Hong Kong', country: 'Hong Kong', rank: 95 },
  { iata: 'MFM', name: 'Macau International', city: 'Macau', country: 'Macau', rank: 65 },
  { iata: 'TPE', name: 'Taipei Taoyuan', city: 'Taipei', country: 'Taiwan', rank: 85 },
  { iata: 'TSA', name: 'Taipei Songshan', city: 'Taipei', country: 'Taiwan', rank: 65 },
  { iata: 'KHH', name: 'Kaohsiung', city: 'Kaohsiung', country: 'Taiwan', rank: 60 },
  { iata: 'ULN', name: 'Ulaanbaatar Chinggis Khaan', city: 'Ulaanbaatar', country: 'Mongolia', rank: 55 },

  // ─── SOUTHEAST ASIA ───
  { iata: 'SIN', name: 'Singapore Changi', city: 'Singapore', country: 'Singapore', rank: 100 },
  { iata: 'BKK', name: 'Bangkok Suvarnabhumi', city: 'Bangkok', country: 'Thailand', rank: 95 },
  { iata: 'DMK', name: 'Bangkok Don Mueang', city: 'Bangkok', country: 'Thailand', rank: 80 },
  { iata: 'HKT', name: 'Phuket', city: 'Phuket', country: 'Thailand', rank: 80 },
  { iata: 'CNX', name: 'Chiang Mai', city: 'Chiang Mai', country: 'Thailand', rank: 65 },
  { iata: 'USM', name: 'Koh Samui', city: 'Koh Samui', country: 'Thailand', rank: 55 },
  { iata: 'KUL', name: 'Kuala Lumpur International', city: 'Kuala Lumpur', country: 'Malaysia', rank: 90 },
  { iata: 'PEN', name: 'Penang', city: 'Penang', country: 'Malaysia', rank: 65 },
  { iata: 'BKI', name: 'Kota Kinabalu', city: 'Kota Kinabalu', country: 'Malaysia', rank: 60 },
  { iata: 'KCH', name: 'Kuching', city: 'Kuching', country: 'Malaysia', rank: 55 },
  { iata: 'CGK', name: 'Jakarta Soekarno-Hatta', city: 'Jakarta', country: 'Indonesia', rank: 90 },
  { iata: 'DPS', name: 'Bali Denpasar Ngurah Rai', city: 'Bali', country: 'Indonesia', rank: 85 },
  { iata: 'SUB', name: 'Surabaya Juanda', city: 'Surabaya', country: 'Indonesia', rank: 65 },
  { iata: 'JOG', name: 'Yogyakarta', city: 'Yogyakarta', country: 'Indonesia', rank: 55 },
  { iata: 'MNL', name: 'Manila Ninoy Aquino', city: 'Manila', country: 'Philippines', rank: 85 },
  { iata: 'CEB', name: 'Cebu Mactan', city: 'Cebu', country: 'Philippines', rank: 70 },
  { iata: 'CRK', name: 'Clark', city: 'Angeles', country: 'Philippines', rank: 60 },
  { iata: 'HAN', name: 'Hanoi Noi Bai', city: 'Hanoi', country: 'Vietnam', rank: 80 },
  { iata: 'SGN', name: 'Ho Chi Minh City Tan Son Nhat', city: 'Ho Chi Minh City', country: 'Vietnam', rank: 85 },
  { iata: 'DAD', name: 'Da Nang', city: 'Da Nang', country: 'Vietnam', rank: 65 },
  { iata: 'PNH', name: 'Phnom Penh', city: 'Phnom Penh', country: 'Cambodia', rank: 60 },
  { iata: 'REP', name: 'Siem Reap Angkor', city: 'Siem Reap', country: 'Cambodia', rank: 60 },
  { iata: 'VTE', name: 'Vientiane Wattay', city: 'Vientiane', country: 'Laos', rank: 50 },
  { iata: 'RGN', name: 'Yangon', city: 'Yangon', country: 'Myanmar', rank: 60 },
  { iata: 'CMB', name: 'Colombo Bandaranaike', city: 'Colombo', country: 'Sri Lanka', rank: 70 },
  { iata: 'KTM', name: 'Kathmandu Tribhuvan', city: 'Kathmandu', country: 'Nepal', rank: 65 },
  { iata: 'DAC', name: 'Dhaka Hazrat Shahjalal', city: 'Dhaka', country: 'Bangladesh', rank: 70 },
  { iata: 'MLE', name: 'Malé Velana', city: 'Malé', country: 'Maldives', rank: 65 },
  { iata: 'ISB', name: 'Islamabad', city: 'Islamabad', country: 'Pakistan', rank: 70 },
  { iata: 'KHI', name: 'Karachi Jinnah', city: 'Karachi', country: 'Pakistan', rank: 70 },
  { iata: 'LHE', name: 'Lahore Allama Iqbal', city: 'Lahore', country: 'Pakistan', rank: 65 },

  // ─── OCEANIA ───
  { iata: 'SYD', name: 'Sydney Kingsford Smith', city: 'Sydney', country: 'Australia', rank: 90 },
  { iata: 'MEL', name: 'Melbourne Tullamarine', city: 'Melbourne', country: 'Australia', rank: 85 },
  { iata: 'BNE', name: 'Brisbane', city: 'Brisbane', country: 'Australia', rank: 80 },
  { iata: 'PER', name: 'Perth', city: 'Perth', country: 'Australia', rank: 75 },
  { iata: 'ADL', name: 'Adelaide', city: 'Adelaide', country: 'Australia', rank: 65 },
  { iata: 'CNS', name: 'Cairns', city: 'Cairns', country: 'Australia', rank: 60 },
  { iata: 'OOL', name: 'Gold Coast', city: 'Gold Coast', country: 'Australia', rank: 60 },
  { iata: 'DRW', name: 'Darwin', city: 'Darwin', country: 'Australia', rank: 50 },
  { iata: 'AKL', name: 'Auckland', city: 'Auckland', country: 'New Zealand', rank: 80 },
  { iata: 'WLG', name: 'Wellington', city: 'Wellington', country: 'New Zealand', rank: 65 },
  { iata: 'CHC', name: 'Christchurch', city: 'Christchurch', country: 'New Zealand', rank: 65 },
  { iata: 'NAN', name: 'Nadi', city: 'Nadi', country: 'Fiji', rank: 55 },
  { iata: 'PPT', name: 'Papeete Faa\'a', city: 'Papeete', country: 'French Polynesia', rank: 55 },
  { iata: 'NOU', name: 'Nouméa La Tontouta', city: 'Nouméa', country: 'New Caledonia', rank: 45 },

  // ─── NORTH AMERICA — USA ───
  { iata: 'JFK', name: 'New York JFK', city: 'New York', country: 'USA', rank: 95 },
  { iata: 'LGA', name: 'New York LaGuardia', city: 'New York', country: 'USA', rank: 80 },
  { iata: 'EWR', name: 'Newark Liberty', city: 'New York', country: 'USA', rank: 85 },
  { iata: 'LAX', name: 'Los Angeles', city: 'Los Angeles', country: 'USA', rank: 95 },
  { iata: 'SFO', name: 'San Francisco', city: 'San Francisco', country: 'USA', rank: 90 },
  { iata: 'OAK', name: 'Oakland', city: 'Oakland', country: 'USA', rank: 65 },
  { iata: 'SJC', name: 'San Jose Mineta', city: 'San Jose', country: 'USA', rank: 65 },
  { iata: 'ORD', name: 'Chicago O\'Hare', city: 'Chicago', country: 'USA', rank: 90 },
  { iata: 'MDW', name: 'Chicago Midway', city: 'Chicago', country: 'USA', rank: 70 },
  { iata: 'MIA', name: 'Miami International', city: 'Miami', country: 'USA', rank: 85 },
  { iata: 'FLL', name: 'Fort Lauderdale', city: 'Fort Lauderdale', country: 'USA', rank: 70 },
  { iata: 'MCO', name: 'Orlando International', city: 'Orlando', country: 'USA', rank: 80 },
  { iata: 'TPA', name: 'Tampa', city: 'Tampa', country: 'USA', rank: 70 },
  { iata: 'ATL', name: 'Atlanta Hartsfield-Jackson', city: 'Atlanta', country: 'USA', rank: 95 },
  { iata: 'DFW', name: 'Dallas Fort Worth', city: 'Dallas', country: 'USA', rank: 90 },
  { iata: 'DAL', name: 'Dallas Love Field', city: 'Dallas', country: 'USA', rank: 65 },
  { iata: 'IAH', name: 'Houston Bush Intercontinental', city: 'Houston', country: 'USA', rank: 85 },
  { iata: 'HOU', name: 'Houston Hobby', city: 'Houston', country: 'USA', rank: 65 },
  { iata: 'DEN', name: 'Denver International', city: 'Denver', country: 'USA', rank: 85 },
  { iata: 'PHX', name: 'Phoenix Sky Harbor', city: 'Phoenix', country: 'USA', rank: 80 },
  { iata: 'LAS', name: 'Las Vegas Harry Reid', city: 'Las Vegas', country: 'USA', rank: 80 },
  { iata: 'SEA', name: 'Seattle Tacoma', city: 'Seattle', country: 'USA', rank: 85 },
  { iata: 'PDX', name: 'Portland International', city: 'Portland', country: 'USA', rank: 70 },
  { iata: 'BOS', name: 'Boston Logan', city: 'Boston', country: 'USA', rank: 85 },
  { iata: 'DCA', name: 'Washington Reagan', city: 'Washington', country: 'USA', rank: 75 },
  { iata: 'IAD', name: 'Washington Dulles', city: 'Washington', country: 'USA', rank: 80 },
  { iata: 'BWI', name: 'Baltimore Washington', city: 'Baltimore', country: 'USA', rank: 70 },
  { iata: 'PHL', name: 'Philadelphia', city: 'Philadelphia', country: 'USA', rank: 75 },
  { iata: 'DTW', name: 'Detroit Wayne County', city: 'Detroit', country: 'USA', rank: 75 },
  { iata: 'MSP', name: 'Minneapolis St. Paul', city: 'Minneapolis', country: 'USA', rank: 75 },
  { iata: 'CLT', name: 'Charlotte Douglas', city: 'Charlotte', country: 'USA', rank: 75 },
  { iata: 'SLC', name: 'Salt Lake City', city: 'Salt Lake City', country: 'USA', rank: 75 },
  { iata: 'STL', name: 'St. Louis Lambert', city: 'St. Louis', country: 'USA', rank: 65 },
  { iata: 'MSY', name: 'New Orleans Louis Armstrong', city: 'New Orleans', country: 'USA', rank: 65 },
  { iata: 'SAN', name: 'San Diego', city: 'San Diego', country: 'USA', rank: 70 },
  { iata: 'AUS', name: 'Austin Bergstrom', city: 'Austin', country: 'USA', rank: 70 },
  { iata: 'BNA', name: 'Nashville', city: 'Nashville', country: 'USA', rank: 70 },
  { iata: 'PIT', name: 'Pittsburgh', city: 'Pittsburgh', country: 'USA', rank: 60 },
  { iata: 'HNL', name: 'Honolulu Daniel Inouye', city: 'Honolulu', country: 'USA', rank: 75 },
  { iata: 'OGG', name: 'Maui Kahului', city: 'Maui', country: 'USA', rank: 60 },
  { iata: 'ANC', name: 'Anchorage Ted Stevens', city: 'Anchorage', country: 'USA', rank: 55 },

  // ─── CANADA ───
  { iata: 'YYZ', name: 'Toronto Pearson', city: 'Toronto', country: 'Canada', rank: 90 },
  { iata: 'YYC', name: 'Calgary', city: 'Calgary', country: 'Canada', rank: 75 },
  { iata: 'YVR', name: 'Vancouver International', city: 'Vancouver', country: 'Canada', rank: 85 },
  { iata: 'YUL', name: 'Montreal Pierre Elliott Trudeau', city: 'Montreal', country: 'Canada', rank: 80 },
  { iata: 'YEG', name: 'Edmonton', city: 'Edmonton', country: 'Canada', rank: 65 },
  { iata: 'YOW', name: 'Ottawa Macdonald-Cartier', city: 'Ottawa', country: 'Canada', rank: 65 },
  { iata: 'YHZ', name: 'Halifax Stanfield', city: 'Halifax', country: 'Canada', rank: 60 },
  { iata: 'YWG', name: 'Winnipeg', city: 'Winnipeg', country: 'Canada', rank: 55 },

  // ─── MEXICO / CENTRAL AMERICA ───
  { iata: 'MEX', name: 'Mexico City Benito Juárez', city: 'Mexico City', country: 'Mexico', rank: 85 },
  { iata: 'NLU', name: 'Mexico City Felipe Ángeles', city: 'Mexico City', country: 'Mexico', rank: 65 },
  { iata: 'CUN', name: 'Cancun', city: 'Cancun', country: 'Mexico', rank: 80 },
  { iata: 'GDL', name: 'Guadalajara', city: 'Guadalajara', country: 'Mexico', rank: 70 },
  { iata: 'MTY', name: 'Monterrey', city: 'Monterrey', country: 'Mexico', rank: 70 },
  { iata: 'SJD', name: 'Los Cabos', city: 'Los Cabos', country: 'Mexico', rank: 65 },
  { iata: 'PVR', name: 'Puerto Vallarta', city: 'Puerto Vallarta', country: 'Mexico', rank: 60 },
  { iata: 'GUA', name: 'Guatemala City La Aurora', city: 'Guatemala City', country: 'Guatemala', rank: 60 },
  { iata: 'SJO', name: 'San José Juan Santamaría', city: 'San José', country: 'Costa Rica', rank: 65 },
  { iata: 'PTY', name: 'Panama City Tocumen', city: 'Panama City', country: 'Panama', rank: 75 },
  { iata: 'SAL', name: 'San Salvador', city: 'San Salvador', country: 'El Salvador', rank: 55 },

  // ─── CARIBBEAN ───
  { iata: 'HAV', name: 'Havana José Martí', city: 'Havana', country: 'Cuba', rank: 65 },
  { iata: 'SDQ', name: 'Santo Domingo Las Américas', city: 'Santo Domingo', country: 'Dominican Republic', rank: 65 },
  { iata: 'PUJ', name: 'Punta Cana', city: 'Punta Cana', country: 'Dominican Republic', rank: 70 },
  { iata: 'MBJ', name: 'Montego Bay Sangster', city: 'Montego Bay', country: 'Jamaica', rank: 60 },
  { iata: 'KIN', name: 'Kingston Norman Manley', city: 'Kingston', country: 'Jamaica', rank: 55 },
  { iata: 'SJU', name: 'San Juan Luis Muñoz Marín', city: 'San Juan', country: 'Puerto Rico', rank: 70 },
  { iata: 'NAS', name: 'Nassau Lynden Pindling', city: 'Nassau', country: 'Bahamas', rank: 60 },
  { iata: 'BGI', name: 'Bridgetown Grantley Adams', city: 'Bridgetown', country: 'Barbados', rank: 55 },
  { iata: 'AUA', name: 'Aruba Queen Beatrix', city: 'Oranjestad', country: 'Aruba', rank: 55 },

  // ─── SOUTH AMERICA ───
  { iata: 'GRU', name: 'São Paulo Guarulhos', city: 'São Paulo', country: 'Brazil', rank: 90 },
  { iata: 'CGH', name: 'São Paulo Congonhas', city: 'São Paulo', country: 'Brazil', rank: 75 },
  { iata: 'GIG', name: 'Rio de Janeiro Galeão', city: 'Rio de Janeiro', country: 'Brazil', rank: 80 },
  { iata: 'SDU', name: 'Rio de Janeiro Santos Dumont', city: 'Rio de Janeiro', country: 'Brazil', rank: 65 },
  { iata: 'BSB', name: 'Brasília', city: 'Brasília', country: 'Brazil', rank: 70 },
  { iata: 'SSA', name: 'Salvador', city: 'Salvador', country: 'Brazil', rank: 60 },
  { iata: 'REC', name: 'Recife Guararapes', city: 'Recife', country: 'Brazil', rank: 60 },
  { iata: 'FOR', name: 'Fortaleza Pinto Martins', city: 'Fortaleza', country: 'Brazil', rank: 60 },
  { iata: 'POA', name: 'Porto Alegre Salgado Filho', city: 'Porto Alegre', country: 'Brazil', rank: 60 },
  { iata: 'CWB', name: 'Curitiba Afonso Pena', city: 'Curitiba', country: 'Brazil', rank: 55 },
  { iata: 'EZE', name: 'Buenos Aires Ezeiza', city: 'Buenos Aires', country: 'Argentina', rank: 80 },
  { iata: 'AEP', name: 'Buenos Aires Aeroparque', city: 'Buenos Aires', country: 'Argentina', rank: 65 },
  { iata: 'COR', name: 'Cordoba', city: 'Cordoba', country: 'Argentina', rank: 55 },
  { iata: 'MVD', name: 'Montevideo Carrasco', city: 'Montevideo', country: 'Uruguay', rank: 60 },
  { iata: 'SCL', name: 'Santiago Arturo Merino Benítez', city: 'Santiago', country: 'Chile', rank: 75 },
  { iata: 'LIM', name: 'Lima Jorge Chávez', city: 'Lima', country: 'Peru', rank: 75 },
  { iata: 'CUZ', name: 'Cusco Alejandro Velasco Astete', city: 'Cusco', country: 'Peru', rank: 60 },
  { iata: 'BOG', name: 'Bogotá El Dorado', city: 'Bogotá', country: 'Colombia', rank: 80 },
  { iata: 'MDE', name: 'Medellín José María Córdova', city: 'Medellín', country: 'Colombia', rank: 70 },
  { iata: 'CTG', name: 'Cartagena Rafael Núñez', city: 'Cartagena', country: 'Colombia', rank: 60 },
  { iata: 'CCS', name: 'Caracas Simón Bolívar', city: 'Caracas', country: 'Venezuela', rank: 60 },
  { iata: 'UIO', name: 'Quito Mariscal Sucre', city: 'Quito', country: 'Ecuador', rank: 65 },
  { iata: 'GYE', name: 'Guayaquil José Joaquín de Olmedo', city: 'Guayaquil', country: 'Ecuador', rank: 55 },
  { iata: 'LPB', name: 'La Paz El Alto', city: 'La Paz', country: 'Bolivia', rank: 55 },
  { iata: 'ASU', name: 'Asunción Silvio Pettirossi', city: 'Asunción', country: 'Paraguay', rank: 50 }
];
